[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 10088456095462536
solc = "0.8.28"
evm_version = "Cancun"
# bytecode_hash = "none"
# cbor_metadata = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 1000

# create2_deployer="0x2F270EAE0146219275190004CdB26482Fc359144" # will see this again and used the modify
# create2_deployer="0x1B150538E943F00127929f7eeB65754f7beB0B6d" # will see this again and used the modify
always_use_create_2_factory = true

# 0x39C2808F0AbE0EcfA2537Eaf07e12310812D6Ef1

# # RPC endpoints
# [rpc_endpoints]
# ethereum = "${ETHEREUM_RPC_URL}"
# arbitrum = "${ARBITRUM_RPC_URL}"
# unichain = "${UNICHAIN_RPC_URL}"
# base = "${BASE_RPC_URL}"

# # Etherscan API keys for verification
# [etherscan]
# ethereum = { key = "${ETHERSCAN_API_KEY}" }
